/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopprojectnet;

import java.awt.Component;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author zmcdo
 */
public class CreateEventPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEventPanel
     */
    public CreateEventPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        labelPlace = new javax.swing.JLabel();
        eventName = new javax.swing.JTextField();
        eventCreateBtn = new javax.swing.JButton();
        eventClearBtn = new javax.swing.JButton();
        eventBackBtn = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        availablePlaces = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        chosenPlacesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPlace.setText("Name:");
        add(labelPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 39, -1, -1));

        eventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameActionPerformed(evt);
            }
        });
        add(eventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 36, 138, -1));

        eventCreateBtn.setText("Create");
        eventCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventCreateBtnActionPerformed(evt);
            }
        });
        add(eventCreateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 335, -1, -1));

        eventClearBtn.setText("Clear");
        eventClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventClearBtnActionPerformed(evt);
            }
        });
        add(eventClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 335, -1, -1));

        eventBackBtn.setText("Back");
        eventBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBackBtnActionPerformed(evt);
            }
        });
        add(eventBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 335, -1, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 16, -1, -1));

        availablePlaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getAvailablePlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(availablePlaces);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 166, 180, -1));

        chosenPlacesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getChosenPlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(chosenPlacesList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 166, 185, -1));

        jLabel1.setText("Available Places:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 128, -1, -1));

        jLabel2.setText("Choosen Places:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 128, -1, -1));

        AddButton.setText("Add >>");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 176, 119, -1));

        jButton2.setText("<< Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 254, -1, -1));

        jButton3.setText("Add All");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 216, 119, -1));
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<Places> chosenPlaces = new ArrayList<>();
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if(availablePlaces.getSelectedIndex() != -1) {
            
            chosenPlaces.add(Database.listPlaces.get(getIndexOfName(availablePlaces.getSelectedValue())));
            
        chosenPlacesList = new javax.swing.JList<>();

        chosenPlacesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getChosenPlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane3.setViewportView(chosenPlacesList);

        availablePlaces = new javax.swing.JList<>();

        availablePlaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getAvailablePlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane2.setViewportView(availablePlaces);

        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                if(chosenPlacesList.getSelectedIndex() != -1) {
            chosenPlaces.remove(Database.listPlaces.get(getIndexOfName(chosenPlacesList.getSelectedValue())));
            
        chosenPlacesList = new javax.swing.JList<>();

        chosenPlacesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getChosenPlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane3.setViewportView(chosenPlacesList);

        availablePlaces = new javax.swing.JList<>();

        availablePlaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getAvailablePlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane2.setViewportView(availablePlaces);

        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean checkEventName(String name) {
        for (Event current : Database.listEvents) {
            if (current.getName().toLowerCase().equals(name.toLowerCase())) {
                return true;
            }
        }
        return false;
    }
    private void eventCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventCreateBtnActionPerformed
        String name = eventName.getText();
        if(!checkEventName(name)) {
            Event newEvent = new Event(eventName.getText(), new ArrayList<PersonPlaces>(), chosenPlaces);
            Database.listEvents.add(newEvent);

            Object[] options = {
                "OK",
                "CREATE ANOTHER"
            };
            Object optionSelected = JOptionPane.showOptionDialog(null, "event created, Click OK to come back to menu or create another", "success", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
            switch (optionSelected.toString()) {
                case "0":
                    Component comp = SwingUtilities.getRoot(this);
                    ((Window) comp).dispose();
                    break;
                case "1":
                    eventName.setText("");
                    chosenPlaces = new ArrayList<Places>();
                    chosenPlacesList = new javax.swing.JList<>();

                    chosenPlacesList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = getChosenPlaces();
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });

                    jScrollPane3.setViewportView(chosenPlacesList);

                    availablePlaces = new javax.swing.JList<>();

                    availablePlaces.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = getAvailablePlaces();
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });

                    jScrollPane2.setViewportView(availablePlaces);
                    break;
            }  
       }
       else {
            String message = "name already exists, please change name";
            JOptionPane.showMessageDialog(new JFrame(), message, "Warning",
            JOptionPane.WARNING_MESSAGE);
            eventName.setText("");
        }
    }//GEN-LAST:event_eventCreateBtnActionPerformed

    private void eventClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventClearBtnActionPerformed
        
        chosenPlaces = new ArrayList<Places>();
        chosenPlacesList = new javax.swing.JList<>();

        chosenPlacesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getChosenPlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane3.setViewportView(chosenPlacesList);

        availablePlaces = new javax.swing.JList<>();

        availablePlaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getAvailablePlaces();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane2.setViewportView(availablePlaces);
        
    }//GEN-LAST:event_eventClearBtnActionPerformed

    private void eventBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventBackBtnActionPerformed
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
    }//GEN-LAST:event_eventBackBtnActionPerformed

    private void eventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameActionPerformed
    private int getIndexOfName (String name) {
        for(Places p:Database.listPlaces) {
            if(p.getName().equals(name)) {
                return Database.listPlaces.indexOf(p);
            }
        }
        return -1;
    } 
        private String[] getChosenPlaces() {
        ArrayList<String> places = new ArrayList<>();
        for(Places p : chosenPlaces) {
            places.add(p.getName());
        }
        String[] temp = new String[places.size()];
        temp = places.toArray(temp);
        return temp;
    }
    private String[] getAvailablePlaces() {
        ArrayList<String> places = new ArrayList<>();
        for(Places p : Database.listPlaces) {
            if(!chosenPlaces.contains(p)) {
                places.add(p.getName());
            }
        }
        String[] temp = new String[places.size()];
        temp = places.toArray(temp);
        System.out.println(places);
        return temp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JList<String> availablePlaces;
    private javax.swing.JList<String> chosenPlacesList;
    private javax.swing.JButton eventBackBtn;
    private javax.swing.JButton eventClearBtn;
    private javax.swing.JButton eventCreateBtn;
    private javax.swing.JTextField eventName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelPlace;
    // End of variables declaration//GEN-END:variables
}
