/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopprojectnet;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zmcdo
 */
public class EventsMenu extends javax.swing.JFrame {

    /**
     * Creates new form EventsMenu
     */
    public EventsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createEventBtn = new javax.swing.JButton();
        addPersonToEventBtn = new javax.swing.JButton();
        infoEventBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(699, 699));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        createEventBtn.setText("Create Event");
        createEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createEventBtn);

        addPersonToEventBtn.setText("Add Person to Event");
        addPersonToEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonToEventBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addPersonToEventBtn);

        infoEventBtn.setText("Info Event");
        infoEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEventBtnActionPerformed(evt);
            }
        });
        getContentPane().add(infoEventBtn);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonToEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonToEventBtnActionPerformed
        if(Database.listEvents.size() > 0 && Database.listPeople.size() > 0) {
            setContentPane(new AddPersonToEvent());
            revalidate();
        }
        else {
            String message = "program has no events or people, create";
            JOptionPane.showMessageDialog(new JFrame(), message, "Warning",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addPersonToEventBtnActionPerformed

    private void createEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventBtnActionPerformed
        setContentPane(new CreateEventPanel());
        revalidate();
    }//GEN-LAST:event_createEventBtnActionPerformed

    private void infoEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEventBtnActionPerformed
        setContentPane(new InfoEventPanel());
        revalidate();
    }//GEN-LAST:event_infoEventBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonToEventBtn;
    private javax.swing.JButton createEventBtn;
    private javax.swing.JButton infoEventBtn;
    // End of variables declaration//GEN-END:variables
}
