/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopprojectnet;

import java.awt.Component;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author zmcdo
 */
public class InfoEventPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoEventPanel
     */
    public InfoEventPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        eventNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        infoEventBackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        placesList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        peopleList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        numberOfPeople = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        placesProfitLabel = new javax.swing.JLabel();
        placesProfit = new javax.swing.JLabel();
        showGuestListBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        guestListJList = new javax.swing.JList<>();

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventNameLabel.setText("Event Name:");
        add(eventNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 75, -1, -1));

        jLabel1.setText("People:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 220, -1, -1));

        jLabel2.setText("Places:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 348, -1, -1));

        infoEventBackBtn.setText("Back");
        infoEventBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEventBackBtnActionPerformed(evt);
            }
        });
        add(infoEventBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 631, -1, -1));

        eventList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getListNameEvents("");
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        eventList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eventList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 42, 186, 109));

        placesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPlacesFromPerson(peopleList.getName(),getEventName());
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        placesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placesListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(placesList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 290, 186, 103));

        peopleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPeopleFromEvent(getEventName());
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        peopleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peopleListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(peopleList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 169, 186, 105));

        jLabel3.setText("Number of people in this place:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 343, -1, -1));

        numberOfPeople.setText("0");
        add(numberOfPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 164, -1));

        jLabel5.setText("Event's Profit:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 59, -1, -1));

        profit.setText("0");
        add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 59, 163, -1));

        placesProfitLabel.setText("Place's profit in this event:");
        add(placesProfitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 290, -1, -1));

        placesProfit.setText("0");
        add(placesProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 78, -1));

        showGuestListBtn.setText("Generate pub's Guest List!");
        showGuestListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGuestListBtnActionPerformed(evt);
            }
        });
        add(showGuestListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 488, -1, -1));

        guestListJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(guestListJList);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 219, 131));
    }// </editor-fold>//GEN-END:initComponents

    private void eventListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventListMouseClicked
        peopleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPeopleFromEvent(getEventName());
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(peopleList); 
        profit.setText(Database.listEvents.get(eventList.getSelectedIndex()).calculateEventReceipt() + " euros");
        numberOfPeople.setText("0");
        placesProfit.setText("0 euros");
    }//GEN-LAST:event_eventListMouseClicked

    private void placesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placesListMouseClicked
        numberOfPeople.setText(Database.listEvents.get(eventList.getSelectedIndex()).countLocal(placesList.getSelectedValue()) +"");
        placesProfit.setText(Database.listEvents.get(eventList.getSelectedIndex()).calculatePlaceReceipt(placesList.getSelectedValue()) +" euros");

    }//GEN-LAST:event_placesListMouseClicked

    private void peopleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peopleListMouseClicked
        placesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPlacesFromPerson(peopleList.getSelectedValue(),getEventName());
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(placesList); 
            guestListJList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {};
                @Override
                public int getSize() { return strings.length; }
                @Override
                public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(guestListJList); 
        numberOfPeople.setText("0");
        placesProfit.setText("0 euros");
    }//GEN-LAST:event_peopleListMouseClicked

    private void infoEventBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEventBackBtnActionPerformed
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();    }//GEN-LAST:event_infoEventBackBtnActionPerformed

    private void showGuestListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGuestListBtnActionPerformed
        if(placesList.getSelectedIndex() != -1 && eventList.getSelectedIndex() != -1) {
            if(!Database.getPlaceFromName(placesList.getSelectedValue()).getClass().toString().toLowerCase().equals("class oopprojectnet.pubs")) {
                    String message = "Place selected isn't a pub!";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog", JOptionPane.ERROR_MESSAGE);
            }
            else {
                Pubs temp = (Pubs) Database.getPlaceFromName(placesList.getSelectedValue());
                guestListJList.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = temp.showGuestList();
                    @Override
                    public int getSize() { return strings.length; }
                    @Override
                    public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane5.setViewportView(guestListJList); 
            }
        }
    }//GEN-LAST:event_showGuestListBtnActionPerformed
    private String stringSlice(int a, int b, String s) {
        String res= "";
        for (int i=a; i<=b; i++) {
            res = res + s.charAt(i);
        }
        return res;
    }
    
    /**
     * Method to get name of the event selected in "eventList" in GUI
     * @return one string with the name of the event
     */
    private String getEventName() {
        if(eventList.getSelectedIndex() != -1 ) {
            return Database.listEvents.get(eventList.getSelectedIndex()).getName();
        }
        else {
            return Database.listEvents.get(0).getName();        
        }
    }
    private String[] getListNameEvents(String search) {
        ArrayList < String > list;
        list = new ArrayList <> ();
        for (Event p: Database.listEvents) {
            if(search.length() != 0){
                if(search.length() <= p.getName().length() && stringSlice(0, search.length()-1, p.getName()).equals(search)) {
                    list.add(p.getName());
                }
            }
            else {
                list.add(p.getName());
            }
        }
        String[] temp = new String[list.size()];
        temp = list.toArray(temp);
        return temp;
    }
    
    /**
     * Method to get all people from one event, receive one string as parameter
     * @param event name of the event you want to pick people
     * @return one array with strings containing the event's people
     */
    private String[] getPeopleFromEvent(String event) {
        ArrayList<String> t = new ArrayList<String>();
        for(Event e : Database.listEvents) {
            if(e.getName().equals(event)) {
                for(PersonPlaces pp : e.getInvitedList()) {
                    t.add(pp.getPerson().getName());
                }
            }
        }
        String[] temp = new String[t.size()];
        temp = t.toArray(temp);
        return temp;
    }
    /**
     * Method to get the places selected from one person in one event
     * @param person the person you want to pick the places
     * @param event the event desired
     * @return one array of strings containing all places from one person in one event
     */
    private String[] getPlacesFromPerson(String person, String event) {
        
        ArrayList<String> t = new ArrayList<String>();
        for(Event e : Database.listEvents) {
            if(e.getName().equals(event)) {
                for(PersonPlaces pp : e.getInvitedList()) {
                    if(pp.getPerson().getName().equals(person)) {
                        for(Places p : pp.getListPlaces()) {
                            t.add(p.getName());
                        }
                    }
                }
            }
        }
        String[] temp = new String[t.size()];
        temp = t.toArray(temp);
        return temp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> eventList;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JList<String> guestListJList;
    private javax.swing.JButton infoEventBackBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel numberOfPeople;
    private javax.swing.JList<String> peopleList;
    private javax.swing.JList<String> placesList;
    private javax.swing.JLabel placesProfit;
    private javax.swing.JLabel placesProfitLabel;
    private javax.swing.JLabel profit;
    private javax.swing.JButton showGuestListBtn;
    // End of variables declaration//GEN-END:variables
}
