/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopprojectnet;

import java.awt.Component;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author zmcdo
 */
public class InfoEventPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoEventPanel
     */
    public InfoEventPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        eventNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        infoEventBackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        placesList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        peopleList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        numberOfPeople = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        placesProfitLabel = new javax.swing.JLabel();
        placesProfit = new javax.swing.JLabel();
        showGuestListBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        guestListJList = new javax.swing.JList<>();

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        eventNameLabel.setText("Event Name:");

        jLabel1.setText("People:");

        jLabel2.setText("Places:");

        infoEventBackBtn.setText("Back");
        infoEventBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEventBackBtnActionPerformed(evt);
            }
        });

        eventList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getListNameEvents("");
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        eventList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eventList);

        placesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPlacesFromPerson(peopleList.getName(),getEventName());
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        placesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placesListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(placesList);

        peopleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPeopleFromEvent(getEventName());
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        peopleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peopleListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(peopleList);

        jLabel3.setText("Number of people in this place:");

        numberOfPeople.setText("0");

        jLabel5.setText("Event's Profit:");

        profit.setText("0");

        placesProfitLabel.setText("Place's profit in this event:");

        placesProfit.setText("0");

        showGuestListBtn.setText("Press to see pub's Guest List!");
        showGuestListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGuestListBtnActionPerformed(evt);
            }
        });

        guestListJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = null;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(guestListJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(eventNameLabel))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(profit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(placesProfitLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(placesProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel3)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(151, 151, 151)
                                                .addComponent(numberOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showGuestListBtn)
                            .addComponent(infoEventBackBtn))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(eventNameLabel)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(profit))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(placesProfitLabel)
                                    .addComponent(placesProfit))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfPeople))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showGuestListBtn)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)))
                .addComponent(infoEventBackBtn)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eventListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventListMouseClicked
        peopleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPeopleFromEvent(getEventName());
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(peopleList); 
        profit.setText(Database.listEvents.get(eventList.getSelectedIndex()).calculateEventReceipt() + " euros");
    }//GEN-LAST:event_eventListMouseClicked

    private void placesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placesListMouseClicked
        numberOfPeople.setText(Database.listEvents.get(eventList.getSelectedIndex()).countLocal(placesList.getSelectedValue()) +"");
        placesProfit.setText(Database.listEvents.get(eventList.getSelectedIndex()).calculatePlaceReceipt(placesList.getSelectedValue()) +" euros");
       /* if(Database.getPlaceFromName(placesList.getSelectedValue()).getClass().toString().toLowerCase().equals("class oopprojectnet.pubs")) {
            jList5.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = personToString(((Pubs)Database.getPlaceFromName(placesList.getSelectedValue())).getGuestList());
                @Override
                public int getSize() { return strings.length; }
                @Override
                public String getElementAt(int i) { return strings[i]; }
            });

            jScrollPane5.setViewportView(jList5);
        }*/
    }//GEN-LAST:event_placesListMouseClicked

    private void peopleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peopleListMouseClicked
        placesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getPlacesFromPerson(peopleList.getSelectedValue(),getEventName());
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(placesList); 
            guestListJList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = null;
                @Override
                public int getSize() { return strings.length; }
                @Override
                public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(guestListJList); 
    }//GEN-LAST:event_peopleListMouseClicked

    private void infoEventBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEventBackBtnActionPerformed
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();    }//GEN-LAST:event_infoEventBackBtnActionPerformed

    private void showGuestListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGuestListBtnActionPerformed
        if(!Database.getPlaceFromName(placesList.getSelectedValue()).getClass().toString().toLowerCase().equals("class oopprojectnet.pubs")) {
                String message = "Place selected isn't a pub!";
                JOptionPane.showMessageDialog(new JFrame(), message, "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else {
            guestListJList.setModel(new javax.swing.AbstractListModel<String>() {
                Pubs temp = (Pubs) Database.getPlaceFromName(placesList.getSelectedValue());
                String[] strings = temp.showGuestList();
                @Override
                public int getSize() { return strings.length; }
                @Override
                public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(guestListJList); 
        }
    }//GEN-LAST:event_showGuestListBtnActionPerformed
    private String stringSlice(int a, int b, String s) {
        String res= "";
        for (int i=a; i<=b; i++) {
            res = res + s.charAt(i);
        }
        return res;
    }
   
    private String[] personToString(ArrayList<Person> list) {
        ArrayList<String> StringList = new ArrayList<>();
        for(Person current:list) {
            StringList.add(current.getName());
        }
        String[] temp = new String[StringList.size()];
        temp = StringList.toArray(temp);
        System.out.println(temp);
        return temp;
    }
    private String getEventName() {
        if(eventList.getSelectedIndex() != -1 ) {
            return Database.listEvents.get(eventList.getSelectedIndex()).getName();
        }
        else {
            return Database.listEvents.get(0).getName();        
        }
    }
    private String[] getListNameEvents(String search) {
        ArrayList < String > list;
        list = new ArrayList <> ();
        for (Event p: Database.listEvents) {
            if(search.length() != 0){
                if(search.length() <= p.getName().length() && stringSlice(0, search.length()-1, p.getName()).equals(search)) {
                    list.add(p.getName());
                }
            }
            else {
                list.add(p.getName());
            }
        }
        String[] temp = new String[list.size()];
        temp = list.toArray(temp);
        return temp;
    }
    private String[] getPeopleFromEvent(String event) {
        ArrayList<String> t = new ArrayList<String>();
        for(Event e : Database.listEvents) {
            if(e.getName().equals(event)) {
                for(PersonPlaces pp : e.getInvitedList()) {
                    t.add(pp.getPerson().getName());
                }
            }
        }
        String[] temp = new String[t.size()];
        temp = t.toArray(temp);
        return temp;
    }
    
    private String[] getPlacesFromPerson(String person, String event) {
        System.out.println(event);
        System.out.println(person);
        ArrayList<String> t = new ArrayList<String>();
        for(Event e : Database.listEvents) {
            if(e.getName().equals(event)) {
                for(PersonPlaces pp : e.getInvitedList()) {
                    if(pp.getPerson().getName().equals(person)) {
                        for(Places p : pp.getListPlaces()) {
                            t.add(p.getName());
                            System.out.println(p.getName());
                        }
                    }
                }
            }
        }
        String[] temp = new String[t.size()];
        temp = t.toArray(temp);
        return temp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> eventList;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JList<String> guestListJList;
    private javax.swing.JButton infoEventBackBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel numberOfPeople;
    private javax.swing.JList<String> peopleList;
    private javax.swing.JList<String> placesList;
    private javax.swing.JLabel placesProfit;
    private javax.swing.JLabel placesProfitLabel;
    private javax.swing.JLabel profit;
    private javax.swing.JButton showGuestListBtn;
    // End of variables declaration//GEN-END:variables
}
