/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopprojectnet;

/**
 *
 * @author almof
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peopleBtn = new javax.swing.JButton();
        placesBtn = new javax.swing.JButton();
        eventsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        peopleBtn.setText("People");
        peopleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleBtnActionPerformed(evt);
            }
        });
        getContentPane().add(peopleBtn);

        placesBtn.setText("Places");
        placesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(placesBtn);

        eventsBtn.setText("Events");
        eventsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(eventsBtn);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peopleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleBtnActionPerformed
        new PeopleMenu().setVisible(true);
    }//GEN-LAST:event_peopleBtnActionPerformed

    private void placesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placesBtnActionPerformed
        new PlacesMenu().setVisible(true);
    }//GEN-LAST:event_placesBtnActionPerformed

    private void eventsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsBtnActionPerformed
        new EventsMenu().setVisible(true);
    }//GEN-LAST:event_eventsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eventsBtn;
    private javax.swing.JButton peopleBtn;
    private javax.swing.JButton placesBtn;
    // End of variables declaration//GEN-END:variables
}
