/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopprojectnet;


/**
 *
 * @author zmcdo
 */
public class PlacesMenu extends javax.swing.JFrame {

    /**
     * Constructor with Places Menu
     */
    public PlacesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPlaceBtn = new javax.swing.JButton();
        editPlaceBtn = new javax.swing.JButton();
        deletePlaceBtn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(699, 699));
        getContentPane().setLayout(new java.awt.GridLayout());

        createPlaceBtn.setText("Create Place");
        createPlaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createPlaceBtn);

        editPlaceBtn.setText("Edit Place");
        editPlaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPlaceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editPlaceBtn);

        deletePlaceBtn.setText("Delete Place");
        deletePlaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlaceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletePlaceBtn);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPlaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaceBtnActionPerformed
        setContentPane(new CreatePlacePanel());
        revalidate();
    }//GEN-LAST:event_createPlaceBtnActionPerformed

    private void editPlaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPlaceBtnActionPerformed
        setContentPane(new EditPlacePanel());
        revalidate();
    }//GEN-LAST:event_editPlaceBtnActionPerformed

    private void deletePlaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlaceBtnActionPerformed
        setContentPane(new DeletePlacePanel());
        revalidate();
    }//GEN-LAST:event_deletePlaceBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPlaceBtn;
    private javax.swing.JButton deletePlaceBtn;
    private javax.swing.JButton editPlaceBtn;
    // End of variables declaration//GEN-END:variables

}
